config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :dashboard, only: %i[show update]
  resources :widgets, only: [:show]
  resources :dealers, only: %i[edit update] do
    resources :reports, controller: :dealer_reports
  end

  resources :report_uploads, only: %i[new create] do
    collection do
      get 'new_admin'
    end
  end

  get 'fullscreen_dashboard/show'

  root 'fullscreen_dashboard#show'
end

app/models/dealer_report.rb
# frozen_string_literal: true

class DealerReport < ApplicationRecord
  belongs_to :dealer

  validates :reported_on, presence: true
end

app/controllers/dealer_reports_controller.rb
# frozen_string_literal: true

class DealerReportsController < ApplicationController
  before_action :set_dealer
  before_action :set_report, only: %i[edit update destroy]

  def index
    authorize @dealer, :show?
    @reports = @dealer.dealer_reports.order(reported_on: :desc)
  end

  def new
    @report = @dealer.dealer_reports.new(reported_on: Date.today)
    authorize @report
  end

  def create
    @report = @dealer.dealer_reports.build(report_params)
    authorize @report

    if @report.save
      flash[:success] = 'Report successfully created'
      redirect_to dealer_reports_url(@dealer)
    else
      render :new
    end
  end

  def edit
    authorize @report
  end

  def update
    authorize @report

    if @report.update(report_params)
      flash[:success] = 'Report successfully updated'
      redirect_to dealer_reports_url(@dealer)
    else
      render :edit
    end
  end

  def destroy
    authorize @report

    @report.destroy!
    flash[:success] = 'Report successfully deleted'
    redirect_to dealer_reports_url(@dealer)
  end

  private

  def set_dealer
    @dealer = Dealer.find(params[:dealer_id])
  end

  def set_report
    @report = DealerReport.find(params[:id])
  end

  def report_params
    params.require(:dealer_report).permit(
      :new_units_volume, :new_units, :used_units_volume, :used_units, :service_volume,
      :parts_volume, :retail_finance_contracts, :creditor_volume, :warranty_volume,
      :other_volume, :batteries_purchases, :ntp_purchases, :dometic_purchases,
      :atlas_purchases, :thiebert_purchases, :lippert_purchases, :other_purchases,
      :reported_on
    )
  end
end

app/helpers/dealer_reports_helper.rb
# frozen_string_literal: true

module DealerReportsHelper
end

app/views/dealer_reports/_form.html.erb
<%= simple_form_for(@report, url: url) do |f| %>
  <% if @report.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h3>

      <ul>
        <% @report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <%= f.label :reported_on %>
                <%= f.date_field :reported_on, class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Annual Retail Sales</h3>
          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <%= f.input :new_units_volume, as: :decimal, label: 'New Units Volume, $' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :new_units %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :used_units_volume, as: :decimal, label: 'Used Units Volume, $' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :used_units %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <%= f.input :service_volume, as: :decimal, label: 'Service Volume, $' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :parts_volume, as: :decimal, label: 'Parts & Accessories, $' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :retail_finance_contracts %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :creditor_volume, as: :decimal, label: 'Creditor Volume, $' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <%= f.input :warranty_volume, as: :decimal, label: 'Warranty Volume, $' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :other_volume, as: :decimal, label: 'Other Business Products, $' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Annual Purchases - Parts & Accessories</h3>
          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <%= f.input :batteries_purchases, label: 'Battaries' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :ntp_purchases, label: 'NTP' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :dometic_purchases, label: 'Dometic' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :atlas_purchases, label: 'Atlas' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-3">
              <div class="form-group">
                <%= f.input :thiebert_purchases, label: 'Thiebert' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :lippert_purchases, label: 'Lippert' %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-group">
                <%= f.input :other_purchases, label: 'Other' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/dealer_reports/edit.html.erb
<h1>Update your report details</h1>

<%= render 'form', url: dealer_report_path(@dealer, @report) %>

app/views/dealer_reports/index.html.erb
<h1>Dealer Reports</h1>

<% if policy(@dealer.dealer_reports.new).new? %>
  <div class="float-right">
    <%= link_to new_dealer_report_path do %>
      <h4>
        <span class="badge badge-success">
          Create new report
        </span>
      </h4>
    <% end %>
  </div>
<% end %>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th rowspan="2">Reported On</th>
      <th colspan="10">Annual Retail Sales</th>
      <th colspan="7">Annual Purchases</th>
      <th rowspan="2">Actions</th>
    </tr>
    <tr>
      <th colspan='2'>New Units</th>
      <th colspan='2'>Used Units</th>
      <th>Service</th>
      <th>Parts & Accessories</th>
      <th>Retail Finance</th>
      <th>Creditor</th>
      <th>Warranty</th>
      <th>Other</th>
      <th>Battaries</th>
      <th>NTP</th>
      <th>Dometic</th>
      <th>Atlas</th>
      <th>Thiebert</th>
      <th>Lippert</th>
      <th>Other</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.reported_on.strftime('%Y, %B %d') %></td>
        <td><%= report.new_units %></td>
        <td>$<%= report.new_units_volume %></td>
        <td><%= report.used_units %></td>
        <td>$<%= report.used_units_volume %></td>
        <td>$<%= report.service_volume %></td>
        <td>$<%= report.parts_volume %></td>
        <td><%= report.retail_finance_contracts %></td>
        <td>$<%= report.creditor_volume %></td>
        <td>$<%= report.warranty_volume %></td>
        <td>$<%= report.other_volume %></td>
        <td><%= report.batteries_purchases %></td>
        <td><%= report.ntp_purchases %></td>
        <td><%= report.dometic_purchases %></td>
        <td><%= report.atlas_purchases %></td>
        <td><%= report.thiebert_purchases %></td>
        <td><%= report.lippert_purchases %></td>
        <td><%= report.other_purchases %></td>
        <td>
          <%= link_to 'edit', edit_dealer_report_path(@dealer, report), target: '_blank' if policy(report).update? %>
          <%= link_to 'delete', dealer_report_path(@dealer, report), method: :delete, data: { confirm: "Are you sure?" } if policy(report).destroy? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dealer_reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', url: dealer_reports_path(@dealer) %>