config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :dashboard, only: %i[show update]
  resources :widgets, only: [:show]
  resources :dealers, only: %i[edit update] do
    resources :reports, controller: :dealer_reports
  end

  resources :report_uploads, only: %i[new create] do
    collection do
      get 'new_admin'
    end
  end

  get 'fullscreen_dashboard/show'

  root 'fullscreen_dashboard#show'
end

app/controllers/report_uploads_controller.rb
# frozen_string_literal: true

class ReportUploadsController < ApplicationController
  before_action :set_importer, only: :create

  def new
    @report = current_user.partner&.current_report
  end

  def new_admin
    return redirect_to root_url unless is_admin?

    year = Date.today.year
    @reports = PartnerReport.includes(:partner).where(year: [year - 1, year])
    @partners_select = @reports
                       .map(&:partner)
                       .compact
                       .map { |pr| [pr.name, pr.id] }
                       .sort_by(&:first)
  end

  def create
    return redirect_to(root_url) unless @importer

    if @importer.call
      render 'operation_logs'
    else
      flash[:error] = @importer.errors_report
      redirect_to new_report_upload_url
    end
  end

  private

  def set_importer
    return if (partner = get_partner).nil?

    if (report = partner.report_for_year(upload_params[:year])).nil?
      flash[:error] = "To start data import you need to have a partner report for #{upload_params[:year]} year"
      return
    end

    @importer = report.importer(upload_params[:file])
  end

  def get_partner
    if upload_params[:admin] == 'true'
      return unless is_admin?

      partner = Partner.find(upload_params[:partner_id])
    elsif (partner = current_user.partner).nil?
      flash[:error] = 'You have no permissions for reports uploading'
    end

    partner
  end

  def is_admin?
    return true if current_user.admin

    flash[:error] = 'You have no permissions for this action'
    false
  end

  def upload_params
    params.require(:report_upload)
  end
end

app/helpers/report_uploads_helper.rb
# frozen_string_literal: true

module ReportUploadsHelper
  def report_data_storage(report)
    div = <<-DIV
      <div hidden='true' id='#{report.partner_id}-#{report.year}'
        data-quick-report="#{quick(report)}"
        data-example='#{report.example.join('<br>')}'>
      </div>
    DIV

    div.html_safe
  end

  def quick(report)
    verb = report.year < Date.today.year ? 'used' : 'uses'
    "The <span class='badge badge-secondary'>#{report.partner.name}</span> partner #{verb} the #{report.type} type of report in the #{report.year} year. Here you can see the example of *.csv file for this type of partner report"
  end
end

app/views/report_uploads/_example.html.erb
<div class="mt-4 mb-4">
  <h3>Report example</h3>
  <p>Here you can see the example of the correct format of the <%= report.type %> csv file:</p>
  <div class="p-3 mb-2 bg-light text-dark">
    <samp>
      <%= report.example.join('<br>').html_safe %>
    </samp>
  </div>
</div>

app/views/report_uploads/new.html.erb
<h1>Upload report</h1>

<%= render partial: 'example', locals: { report: @report } %>

<%= simple_form_for(:report_upload, url: report_uploads_path) do |f| %>

  <div class="form-group">
    <%= f.input :year, as: :radio_buttons, collection: [Date.today.year, Date.today.year - 1], checked: Date.today.year, label: 'Year of report' %>
  </div>

  <div class="form-group">
    <div class="custom-file">
      <%= f.file_field :file, label: 'Report', class: 'custom-file-input form-control-md' %>
      <%= f.label :file, 'Choose file', class: 'custom-file-label' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Upload', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/report_uploads/new_admin.html.erb
<%= javascript_pack_tag "admin_upload_reports" %>

<div class="container-fluid">
  <h1>Upload report as admin</h1>

  <div class="mt-4 mb-4">
    <% @reports.each do |report| %>
      <%= report_data_storage(report) %>
    <% end %>

    <h3>Report example</h3>
    <p id='quick-report'></p>
    <div class="p-3 mb-2 bg-light text-dark">
      <samp>

      </samp>
    </div>
  </div>

  <%= simple_form_for(:report_upload, url: report_uploads_path) do |f| %>
    <%= f.hidden_field :admin, value: true %>

    <div class="form-group">
      <%= f.input :year, as: :radio_buttons, collection: [Date.today.year, Date.today.year - 1], checked: params[:year] || Date.today.year, label: 'Year of report' %>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <%= f.input :partner_id, collection: @partners_select, class: 'form-control', prompt: 'Select partner', label: false, selected: params[:partner_id] %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <div class="custom-file">
            <%= f.file_field :file, label: 'Report', class: 'custom-file-input form-control-md' %>
            <%= f.label :file, 'Choose file', class: 'custom-file-label' %>
          </div>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit 'Upload', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/report_uploads/operation_logs.html.erb
<h1><%= @importer.name %> Operation Logs</h1>

<h3><%= @importer.operation_stats %></h3>

<figure class="highlight">
  <pre><code>
    <% @importer.logs.each do |line| %>
      <span class="nx"><%= line[:data_item] %>: <%= line[:message] %></span>
    <% end %>
  </code></pre>
</figure>