config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :dashboard, only: %i[show update]
  resources :widgets, only: [:show]
  resources :dealers, only: %i[edit update] do
    resources :reports, controller: :dealer_reports
  end

  resources :report_uploads, only: %i[new create] do
    collection do
      get 'new_admin'
    end
  end

  get 'fullscreen_dashboard/show'

  root 'fullscreen_dashboard#show'
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  before_action :authenticate_user!, except: [:report]
  before_action :set_widgets, only: %i[report show]

  def show; end

  def update
    current_user.update_dashboard!(widgets_hash)
  end

  private

  def current_user
    return User.find(params[:user_id]).try(:decorate) if params[:user_id]

    super
  end

  def set_widgets
    @widgets = current_user.widgets
  end

  def widgets_hash
    return {} unless params[:dashboard]

    params[:dashboard].to_unsafe_h
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/views/dashboards/show.html.erb
<% content_for :head do %>
  <%= stylesheet_pack_tag 'dashboards', media: :all %>
  <%= javascript_pack_tag 'dashboards' %>
<% end %>

<% content_for :top_menu do %>
  <div class="btn-group">
    <button aria-expanded="false" aria-haspopup="true" class="btn btn-primary-outline dropdown-toggle" data-toggle="dropdown" type="button">
      <i class="fa fa-plus"></i>
    </button>
    <div class="dropdown-menu" id="widget-list">
      <% @widgets.each do |widget| %>
        <%= link_to widget_path(format: :json, id: widget.id),
                    class: "dropdown-item #{current_user.dashboard_widget_opened?(widget.identifier)? 'disabled' : ''}",
                    data: { identifier: widget.identifier } do %>
            <i class="fa <%= widget.icon %>"></i>
            <%= widget.name %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<section id="grid">
  <div class="grid-stack">
    <% @widgets.each do |widget| %>
      <% if current_user.dashboard_widget_opened?(widget.identifier) %>
        <% settings = current_user.dashboard_widget_settings(widget.identifier) %>
        <div class="grid-stack-item" gs-x="<%= settings[:x_coordinate] %>" gs-y="<%= settings[:y_coordinate] %>" gs-w="<%= settings[:width] %>" gs-h="<%= settings[:height] %>">
          <div class="grid-stack-item-content">
            <%= render partial: 'widgets/custom_widget',
                       locals: { chart_url: widget.processed_chart_url(current_user),
                                 identifier: widget.identifier,
                                 name: widget.name } %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>