config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :dashboard, only: %i[show update]
  resources :widgets, only: [:show]
  resources :dealers, only: %i[edit update] do
    resources :reports, controller: :dealer_reports
  end

  resources :report_uploads, only: %i[new create] do
    collection do
      get 'new_admin'
    end
  end

  get 'fullscreen_dashboard/show'

  root 'fullscreen_dashboard#show'
end

app/views/layouts/partials/_dashboard_nav.html.erb
<li class="c-header-nav-item px-3">
  <%= link_to dashboard_path, class: 'c-header-nav-link' do %>
    <i class='nav-icon cil-speedometer'></i>
    <%= t(:dashboard) %>
  <% end %>
</li>
<% @fullscreen_widgets.each do |widget| %>
  <li class="c-header-nav-item px-3">
    <%= link_to fullscreen_dashboard_show_path(url: widget.chart_url), class: 'c-header-nav-link' do %>
      <i class='nav-icon <%= widget.icon %>'></i>
      <%= widget.name %>
    <% end %>
  </li>
<% end %>

app/views/layouts/partials/_flash_danger.html.erb
<div class='alert alert-danger alert-dismissible' role='alert'>
  <button class='close' aria-label='Close' data-dismiss='alert' type='button'>
    <span aria-hidden='true'>&times;</span>
  </button>
  <%= message %>
</div>

app/views/layouts/partials/_flash_error.html.erb
<div class='alert alert-danger alert-dismissible'>
  <button class='close' aria-label='Close' data-dismiss='alert' type='button'>
    <span aria-hidden='true'>&times;</span>
  </button>
  <%= message %>
</div>

app/views/layouts/partials/_flash_info.html.erb
<div class='alert alert-info alert-white alert-dismissible' role='alert'>
  <button class='close' aria-label='Close' data-dismiss='alert' type='button'>
    <span aria-hidden='true'>&times;</span>
  </button>
  <%= message %>
</div>

app/views/layouts/partials/_flash_notice.html.erb
<div class='alert alert-warning alert-dismissible'>
  <button class='close' aria-label='Close' data-dismiss='alert' type='button'>
    <span aria-hidden='true'>&times;</span>
  </button>
  <%= message %>
</div>

app/views/layouts/partials/_flash_success.html.erb
<div class='alert alert-success alert-white alert-dismissible' role='alert'>
  <button class='close' aria-label='Close' data-dismiss='alert' type='button'>
    <span aria-hidden='true'>&times;</span>
  </button>
  <%= message %>
</div>

app/views/layouts/partials/_flash_warning.html.erb
<div class='alert alert-warning alert-white alert-dismissible' role='alert'>
  <button class='close' aria-label='Close' data-dismiss='alert' type='button'>
    <span aria-hidden='true'>&times;</span>
  </button>
  <%= message %>
</div>

app/views/layouts/partials/_flashes.html.erb
<% if flash[:success] %>
  <%= render partial: 'layouts/partials/flash_success', locals: { message: flash[:success] } %>
<% end %>
<% if flash[:notice] %>
  <%= render partial: 'layouts/partials/flash_info', locals: { message: flash[:notice] } %>
<% end %>
<% if flash[:alert] %>
  <%= render partial: 'layouts/partials/flash_warning', locals: { message: flash[:alert] } %>
<% end %>
<% if flash[:error] %>
  <%= render partial: 'layouts/partials/flash_danger', locals: { message: flash[:error] } %>
<% end %>

app/views/layouts/partials/_head.html.erb
<title>RV Care</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/partials/_navigation.html.erb
<div id="sidebar" class='c-sidebar c-sidebar-light'>
  <ul class='c-sidebar-nav'>
    <li class="c-sidebar-nav-title"><%= t(:management) %></li>
    <li class="c-sidebar-nav-item">
      <%= link_to fullscreen_dashboard_show_path, class: 'c-sidebar-nav-link' do %>
        <i class='c-sidebar-nav-icon cil-speedometer'></i>
        <%= t(:dashboard) %>
      <% end %>
    </li>
    <% if current_user.partner&.current_report %>
      <li class='c-sidebar-nav-item'>
        <%= link_to new_report_upload_path, class: 'c-sidebar-nav-link' do %>
          <i class='c-sidebar-nav-icon cil-spreadsheet'></i>
          <%= t(:upload_report) %>
        <% end %>
      </li>
    <% end %>

    <li class='c-sidebar-nav-item mt-auto'>
      <a href="#" class="c-sidebar-nav-link">
        <i class="c-sidebar-nav-icon cil-user"></i>
        <%= t(:profile) %>
      </a>
    </li>

    <% if current_user.has_role?(:admin) %>
      <li class='c-sidebar-nav-item'>
        <%= link_to admin_root_path, class: 'c-sidebar-nav-link' do %>
          <i class='c-sidebar-nav-icon cil-lock-locked'></i>
          <%= t(:admin) %>
        <% end %>
      </li>
    <% end %>

    <li class='c-sidebar-nav-item'>
      <%= link_to destroy_user_session_path, :method => :delete, class: "c-sidebar-nav-link" do %>
        <i class="c-sidebar-nav-icon cil-power-standby"></i>
        <%= t(:logout) %>
      <% end %>
    </li>

  </ul>
</div>